### ISSUE TITLE
TypeMapping for List<IWebElement> collection throws exception

### ISSUE THREAD

**Issue by xsmirnovx** [davidwhitney/Passenger#11]
When doing stuff like this
```
[CssSelector(".blog-post-title-on-index")]
public virtual List<IWebElement> Posts { get; set; }
```
you'll catch "**System.MissingMethodException: Cannot create an instance of an interface**" instead of a collection of IWebElements.

Passenger.Test.Usage.ExampleUsageTest reproduces this problem.

I've found a workaround for this to use readonly collection instead of list:
```
[CssSelector(".blog-post-title-on-index")]
public virtual ReadOnlyCollection<IWebElement> Posts { get; set; }
```

but this seems not obvious.

**Comment by davidwhitney** [comment]
I'm quite surprised that the ReadOnlyCollection works at all - does that actually function? I'm presuming the error is trying to create an instance of "IWebElement" - I'll reproduce this now and take a look.

**Comment by davidwhitney** [comment]
Right, found and fixed a bug where we were trying to incorrectly do some wrapping. Publishing to nuget in the next 10-20.

**Comment by xsmirnovx** [comment]
Actually I was able to fix it, can create a pull request for you to take a look.
The thing is that Selenium FindElements actually returns IReadOnlyCollection<IWebDriver> while Passenger expects List<IWebDriver>. At least Unit tests are written this way:
```
var domElements = new List<IWebElement>
{
    new PhantomJSWebElement(null, null),
    new FirefoxWebElement(null, null),
    new PhantomJSWebElement(null, null)
});

```

And the error happens this way:

```
// when we try to map
[CssSelector(".blog-post-title-on-index")]
public virtual List<IWebElement> Posts { get; set; }

// the following happens:
SelectElement(Attribute attr, PropertyInfo property) =>
TypeMapping.ReturnOrMap(elements, property.PropertyType) =>
BuildCollectionOfWrappers(object sourceElement, Type targetType)

// and here in BuildCollectionOfWrappers we have the following
var elementType = GetElementType(targetType); // will be IWebElement
...
foreach (var item in ((IEnumerable) sourceElement))
{
    passengerItems.Add(WrapIntoPassengerElement(item, elementType));
}
// and then we get into this function
private static IPassengerElement WrapIntoPassengerElement(object singleElement, Type targetType)
{
    var wrapper = (IPassengerElement)Activator.CreateInstance(targetType); // throws exception
// Here we are trying to create IWebElement instance and cast it to IPassengerElement

```

And ReadOnlyCollection works because when we using it

```
[CssSelector(".blog-post-title-on-index")]
public virtual ReadOnlyCollection<IWebElement> Posts { get; set; }

// then in SelectElement(Attribute attr, PropertyInfo property)
// this codition is true
if (property.PropertyType == elements.GetType())
{
    return elements;
}

// and thus we don't get into TypeMapping.ReturnOrMap =>
// BuildCollectionOfWrappers 

```
Sorry for many words, hope this helps.

**Comment by xsmirnovx** [comment]
Oh, you've already fixed it )

**Comment by davidwhitney** [comment]
Ha yep, pretty much exactly what you pointed out ;)
Package is up here - https://www.nuget.org/packages/Passenger/1.0.30

**Comment by xsmirnovx** [comment]
Haha, you've fixed it while I was typing all this )
Thanks!
