### ISSUE TITLE
Allow URI to be specified without attributes

### ISSUE THREAD

**Issue by rcknight** [davidwhitney/Passenger#2]
Spent a little time this afternoon tinkering with Passenger after watching your Youtube video, first impressions are good :)

Seems like it would be useful to be able to use a single model to test against various addresses... how about allowing a `Uri` to be passed to `StartTestAt`, which can be used either instead of an attribute on the class, or to override it when it does exist?

I'd be happy to send a pull request if you think it is a reasonable idea.

**Comment by davidwhitney** [comment]
Sounds like a good idea - happy to take a PR :)
