### ISSUE TITLE
Relative urls and VerifyRedirectionTo 

### ISSUE THREAD

**Issue by kevinjpluck** [davidwhitney/Passenger#9]
I have the following scenario:

/foobar/signin which sould redirect to /foobar

The VerifyRedirectionTo method checks if current url (/foobar/signin) contains next url (/foobar).  Which it does even though the redirect didn't happen.

**Comment by davidwhitney** [comment]
I feel like these should probably have regex-style constraints - I'll sleep on it over the weekend :+1:

**Comment by davidwhitney** [comment]
Apologies for the huge delay in this - I er.. moved house and got married ;) Excuses excuses - implementing this now.

**Comment by davidwhitney** [comment]
I've added an extra verification pattern property to the Uri attribute, this will allow you to specify your own regular expression to do this kind of matching,

Docs:

The Uri attribute supports an optional verification pattern regular expression - if you provide one, any calls to verify page transitions will validate against this regex, allowing you finer grained control over checking for correct page transitions. Setting up a verification pattern is easy, just provide it as a second parameter in your Uri attribute declaration.

```csharp
[Uri("http://tempuri.org", "http://tempuri\\.[a-z]+")]
```

Published on NuGet Passenger.1.0.28.0.nupkg
